import { Injectable } from '@angular/core';

export class Suburb {
  constructor(public postcode: number, public state: string, public vicSuburb: string) { }
}

@Injectable()
export class SuburbsService {

  constructor() { }


  createDb(){
    const suburbs : Suburb[] = [
      {
         "postcode":3265,
         "state":"VIC",
         "vicSuburb":"CUDGEE"
      },
      {
         "postcode":3106,
         "state":"VIC",
         "vicSuburb":"TEMPLESTOWE"
      },
      {
         "postcode":3266,
         "state":"VIC",
         "vicSuburb":"NAROGHID"
      },
      {
         "postcode":3008,
         "state":"VIC",
         "vicSuburb":"DOCKLANDS"
      },
      {
         "postcode":3064,
         "state":"VIC",
         "vicSuburb":"KALKALLO"
      },
      {
         "postcode":3036,
         "state":"VIC",
         "vicSuburb":"KEILOR"
      },
      {
         "postcode":3191,
         "state":"VIC",
         "vicSuburb":"SANDRINGHAM"
      },
      {
         "postcode":3084,
         "state":"VIC",
         "vicSuburb":"EAGLEMONT"
      },
      {
         "postcode":3223,
         "state":"VIC",
         "vicSuburb":"INDENTED HEAD"
      },
      {
         "postcode":3139,
         "state":"VIC",
         "vicSuburb":"DON VALLEY"
      },
      {
         "postcode":3148,
         "state":"VIC",
         "vicSuburb":"CHADSTONE"
      },
      {
         "postcode":3198,
         "state":"VIC",
         "vicSuburb":"SEAFORD"
      },
      {
         "postcode":3286,
         "state":"VIC",
         "vicSuburb":"RIPPONHURST"
      },
      {
         "postcode":3049,
         "state":"VIC",
         "vicSuburb":"ATTWOOD"
      },
      {
         "postcode":3221,
         "state":"VIC",
         "vicSuburb":"BATESFORD"
      },
      {
         "postcode":3073,
         "state":"VIC",
         "vicSuburb":"RESERVOIR NORTH"
      },
      {
         "postcode":3159,
         "state":"VIC",
         "vicSuburb":"SELBY"
      },
      {
         "postcode":3279,
         "state":"VIC",
         "vicSuburb":"WANGOOM"
      },
      {
         "postcode":3289,
         "state":"VIC",
         "vicSuburb":"PENSHURST"
      },
      {
         "postcode":3109,
         "state":"VIC",
         "vicSuburb":"DONCASTER EAST"
      },
      {
         "postcode":3268,
         "state":"VIC",
         "vicSuburb":"NIRRANDA EAST"
      },
      {
         "postcode":3127,
         "state":"VIC",
         "vicSuburb":"MONT ALBERT"
      },
      {
         "postcode":3042,
         "state":"VIC",
         "vicSuburb":"KEILOR PARK"
      },
      {
         "postcode":3087,
         "state":"VIC",
         "vicSuburb":"WATSONIA"
      },
      {
         "postcode":3218,
         "state":"VIC",
         "vicSuburb":"HERNE HILL"
      },
      {
         "postcode":3031,
         "state":"VIC",
         "vicSuburb":"FLEMINGTON"
      },
      {
         "postcode":3204,
         "state":"VIC",
         "vicSuburb":"BENTLEIGH"
      },
      {
         "postcode":3260,
         "state":"VIC",
         "vicSuburb":"LESLIE MANOR"
      },
      {
         "postcode":3124,
         "state":"VIC",
         "vicSuburb":"CAMBERWELL"
      },
      {
         "postcode":3281,
         "state":"VIC",
         "vicSuburb":"GRASSMERE"
      },
      {
         "postcode":3064,
         "state":"VIC",
         "vicSuburb":"DONNYBROOK"
      },
      {
         "postcode":3237,
         "state":"VIC",
         "vicSuburb":"WEEAPROINAH"
      },
      {
         "postcode":3195,
         "state":"VIC",
         "vicSuburb":"ASPENDALE GARDENS"
      },
      {
         "postcode":3028,
         "state":"VIC",
         "vicSuburb":"ALTONA MEADOWS"
      },
      {
         "postcode":3276,
         "state":"VIC",
         "vicSuburb":"WOOLSTHORPE"
      },
      {
         "postcode":3240,
         "state":"VIC",
         "vicSuburb":"PARAPARAP"
      },
      {
         "postcode":3160,
         "state":"VIC",
         "vicSuburb":"BELGRAVE SOUTH"
      },
      {
         "postcode":3091,
         "state":"VIC",
         "vicSuburb":"YARRAMBAT"
      },
      {
         "postcode":3195,
         "state":"VIC",
         "vicSuburb":"BRAESIDE"
      },
      {
         "postcode":3013,
         "state":"VIC",
         "vicSuburb":"YARRAVILLE"
      },
      {
         "postcode":3037,
         "state":"VIC",
         "vicSuburb":"SYDENHAM"
      },
      {
         "postcode":3131,
         "state":"VIC",
         "vicSuburb":"FOREST HILL"
      },
      {
         "postcode":3215,
         "state":"VIC",
         "vicSuburb":"GEELONG NORTH"
      },
      {
         "postcode":3218,
         "state":"VIC",
         "vicSuburb":"MANIFOLD HEIGHTS"
      },
      {
         "postcode":3228,
         "state":"VIC",
         "vicSuburb":"BELLS BEACH"
      },
      {
         "postcode":3271,
         "state":"VIC",
         "vicSuburb":"DUNDONNELL"
      },
      {
         "postcode":3260,
         "state":"VIC",
         "vicSuburb":"BOSTOCKS CREEK"
      },
      {
         "postcode":3284,
         "state":"VIC",
         "vicSuburb":"ORFORD"
      },
      {
         "postcode":3269,
         "state":"VIC",
         "vicSuburb":"PORT CAMPBELL"
      },
      {
         "postcode":3206,
         "state":"VIC",
         "vicSuburb":"ALBERT PARK"
      },
      {
         "postcode":3231,
         "state":"VIC",
         "vicSuburb":"FAIRHAVEN"
      },
      {
         "postcode":3277,
         "state":"VIC",
         "vicSuburb":"NARINGAL"
      },
      {
         "postcode":3220,
         "state":"VIC",
         "vicSuburb":"NEWTOWN"
      },
      {
         "postcode":3249,
         "state":"VIC",
         "vicSuburb":"CORAGULAC"
      },
      {
         "postcode":3215,
         "state":"VIC",
         "vicSuburb":"BELL POST HILL"
      },
      {
         "postcode":3205,
         "state":"VIC",
         "vicSuburb":"SOUTH MELBOURNE"
      },
      {
         "postcode":3055,
         "state":"VIC",
         "vicSuburb":"BRUNSWICK SOUTH"
      },
      {
         "postcode":3225,
         "state":"VIC",
         "vicSuburb":"SWAN ISLAND"
      },
      {
         "postcode":3260,
         "state":"VIC",
         "vicSuburb":"GNOTUK"
      },
      {
         "postcode":3238,
         "state":"VIC",
         "vicSuburb":"LAVERS HILL"
      },
      {
         "postcode":3175,
         "state":"VIC",
         "vicSuburb":"DANDENONG EAST"
      },
      {
         "postcode":3268,
         "state":"VIC",
         "vicSuburb":"NIRRANDA SOUTH"
      },
      {
         "postcode":3283,
         "state":"VIC",
         "vicSuburb":"SOUTHERN CROSS"
      },
      {
         "postcode":3037,
         "state":"VIC",
         "vicSuburb":"DELAHEY"
      },
      {
         "postcode":3135,
         "state":"VIC",
         "vicSuburb":"BEDFORD ROAD"
      },
      {
         "postcode":3199,
         "state":"VIC",
         "vicSuburb":"FRANKSTON HEIGHTS"
      },
      {
         "postcode":3132,
         "state":"VIC",
         "vicSuburb":"RANGEVIEW"
      },
      {
         "postcode":3083,
         "state":"VIC",
         "vicSuburb":"BUNDOORA"
      },
      {
         "postcode":3212,
         "state":"VIC",
         "vicSuburb":"LARA"
      },
      {
         "postcode":3294,
         "state":"VIC",
         "vicSuburb":"VICTORIA POINT"
      },
      {
         "postcode":3233,
         "state":"VIC",
         "vicSuburb":"SKENES CREEK"
      },
      {
         "postcode":3056,
         "state":"VIC",
         "vicSuburb":"BRUNSWICK"
      },
      {
         "postcode":3221,
         "state":"VIC",
         "vicSuburb":"ANAKIE"
      },
      {
         "postcode":3271,
         "state":"VIC",
         "vicSuburb":"PURA PURA"
      },
      {
         "postcode":3243,
         "state":"VIC",
         "vicSuburb":"WHOOREL"
      },
      {
         "postcode":3162,
         "state":"VIC",
         "vicSuburb":"HOPETOUN GARDENS"
      },
      {
         "postcode":3273,
         "state":"VIC",
         "vicSuburb":"HEXHAM"
      },
      {
         "postcode":3030,
         "state":"VIC",
         "vicSuburb":"COCOROC"
      },
      {
         "postcode":3083,
         "state":"VIC",
         "vicSuburb":"LA TROBE UNIVERSITY"
      },
      {
         "postcode":3215,
         "state":"VIC",
         "vicSuburb":"NORTH GEELONG"
      },
      {
         "postcode":3222,
         "state":"VIC",
         "vicSuburb":"CURLEWIS"
      },
      {
         "postcode":3243,
         "state":"VIC",
         "vicSuburb":"BARWON DOWNS"
      },
      {
         "postcode":3204,
         "state":"VIC",
         "vicSuburb":"MCKINNON"
      },
      {
         "postcode":3128,
         "state":"VIC",
         "vicSuburb":"HOUSTON"
      },
      {
         "postcode":3015,
         "state":"VIC",
         "vicSuburb":"NEWPORT"
      },
      {
         "postcode":3018,
         "state":"VIC",
         "vicSuburb":"ALTONA"
      },
      {
         "postcode":3078,
         "state":"VIC",
         "vicSuburb":"FAIRFIELD"
      },
      {
         "postcode":3131,
         "state":"VIC",
         "vicSuburb":"BRENTFORD SQUARE"
      },
      {
         "postcode":3249,
         "state":"VIC",
         "vicSuburb":"WOOL WOOL"
      },
      {
         "postcode":3231,
         "state":"VIC",
         "vicSuburb":"MOGGS CREEK"
      },
      {
         "postcode":3219,
         "state":"VIC",
         "vicSuburb":"THOMSON"
      },
      {
         "postcode":3164,
         "state":"VIC",
         "vicSuburb":"DANDENONG SOUTH"
      },
      {
         "postcode":3281,
         "state":"VIC",
         "vicSuburb":"BUSHFIELD"
      },
      {
         "postcode":3073,
         "state":"VIC",
         "vicSuburb":"KEON PARK"
      },
      {
         "postcode":3073,
         "state":"VIC",
         "vicSuburb":"RESERVOIR SOUTH"
      },
      {
         "postcode":3169,
         "state":"VIC",
         "vicSuburb":"CLARINDA"
      },
      {
         "postcode":3053,
         "state":"VIC",
         "vicSuburb":"CARLTON SOUTH"
      },
      {
         "postcode":3064,
         "state":"VIC",
         "vicSuburb":"CRAIGIEBURN"
      },
      {
         "postcode":3121,
         "state":"VIC",
         "vicSuburb":"CREMORNE"
      },
      {
         "postcode":3268,
         "state":"VIC",
         "vicSuburb":"COORIEMUNGLE"
      },
      {
         "postcode":3222,
         "state":"VIC",
         "vicSuburb":"DRYSDALE"
      },
      {
         "postcode":3278,
         "state":"VIC",
         "vicSuburb":"PURNIM WEST"
      },
      {
         "postcode":3237,
         "state":"VIC",
         "vicSuburb":"YUULONG"
      },
      {
         "postcode":3030,
         "state":"VIC",
         "vicSuburb":"POINT COOK"
      },
      {
         "postcode":3197,
         "state":"VIC",
         "vicSuburb":"CARRUM"
      },
      {
         "postcode":3199,
         "state":"VIC",
         "vicSuburb":"FRANKSTON SOUTH"
      },
      {
         "postcode":3048,
         "state":"VIC",
         "vicSuburb":"MEADOW HEIGHTS"
      },
      {
         "postcode":3282,
         "state":"VIC",
         "vicSuburb":"ILLOWA"
      },
      {
         "postcode":3221,
         "state":"VIC",
         "vicSuburb":"WYE RIVER"
      },
      {
         "postcode":3219,
         "state":"VIC",
         "vicSuburb":"BREAKWATER"
      },
      {
         "postcode":3089,
         "state":"VIC",
         "vicSuburb":"DIAMOND CREEK"
      },
      {
         "postcode":3187,
         "state":"VIC",
         "vicSuburb":"BRIGHTON EAST"
      },
      {
         "postcode":3040,
         "state":"VIC",
         "vicSuburb":"ESSENDON"
      },
      {
         "postcode":3204,
         "state":"VIC",
         "vicSuburb":"ORMOND"
      },
      {
         "postcode":3241,
         "state":"VIC",
         "vicSuburb":"WINCHELSEA SOUTH"
      },
      {
         "postcode":3038,
         "state":"VIC",
         "vicSuburb":"TAYLORS LAKES"
      },
      {
         "postcode":3130,
         "state":"VIC",
         "vicSuburb":"LABURNUM"
      },
      {
         "postcode":3145,
         "state":"VIC",
         "vicSuburb":"MALVERN EAST"
      },
      {
         "postcode":3241,
         "state":"VIC",
         "vicSuburb":"WURDIBOLUC"
      },
      {
         "postcode":3186,
         "state":"VIC",
         "vicSuburb":"BRIGHTON NORTH"
      },
      {
         "postcode":3099,
         "state":"VIC",
         "vicSuburb":"STRATHEWEN"
      },
      {
         "postcode":3222,
         "state":"VIC",
         "vicSuburb":"CLIFTON SPRINGS"
      },
      {
         "postcode":3128,
         "state":"VIC",
         "vicSuburb":"BOX HILL SOUTH"
      },
      {
         "postcode":3044,
         "state":"VIC",
         "vicSuburb":"PASCOE VALE SOUTH"
      },
      {
         "postcode":3227,
         "state":"VIC",
         "vicSuburb":"BARWON HEADS"
      },
      {
         "postcode":3222,
         "state":"VIC",
         "vicSuburb":"MARCUS HILL"
      },
      {
         "postcode":3073,
         "state":"VIC",
         "vicSuburb":"RESERVOIR"
      },
      {
         "postcode":3260,
         "state":"VIC",
         "vicSuburb":"TESBURY"
      },
      {
         "postcode":3282,
         "state":"VIC",
         "vicSuburb":"KOROIT"
      },
      {
         "postcode":3194,
         "state":"VIC",
         "vicSuburb":"MENTONE EAST"
      },
      {
         "postcode":3107,
         "state":"VIC",
         "vicSuburb":"TEMPLESTOWE LOWER"
      },
      {
         "postcode":3143,
         "state":"VIC",
         "vicSuburb":"ARMADALE NORTH"
      },
      {
         "postcode":3021,
         "state":"VIC",
         "vicSuburb":"ST ALBANS"
      },
      {
         "postcode":3163,
         "state":"VIC",
         "vicSuburb":"GLEN HUNTLY"
      },
      {
         "postcode":3223,
         "state":"VIC",
         "vicSuburb":"PORTARLINGTON"
      },
      {
         "postcode":3153,
         "state":"VIC",
         "vicSuburb":"BAYSWATER NORTH"
      },
      {
         "postcode":3220,
         "state":"VIC",
         "vicSuburb":"SOUTH GEELONG"
      },
      {
         "postcode":3204,
         "state":"VIC",
         "vicSuburb":"PATTERSON"
      },
      {
         "postcode":3102,
         "state":"VIC",
         "vicSuburb":"KEW EAST"
      },
      {
         "postcode":3294,
         "state":"VIC",
         "vicSuburb":"WOODHOUSE"
      },
      {
         "postcode":3285,
         "state":"VIC",
         "vicSuburb":"CODRINGTON"
      },
      {
         "postcode":3260,
         "state":"VIC",
         "vicSuburb":"STONYFORD"
      },
      {
         "postcode":3086,
         "state":"VIC",
         "vicSuburb":"LA TROBE UNIVERSITY"
      },
      {
         "postcode":3285,
         "state":"VIC",
         "vicSuburb":"TOOLONG"
      },
      {
         "postcode":3189,
         "state":"VIC",
         "vicSuburb":"MOORABBIN"
      },
      {
         "postcode":3241,
         "state":"VIC",
         "vicSuburb":"BAMBRA"
      },
      {
         "postcode":3079,
         "state":"VIC",
         "vicSuburb":"IVANHOE"
      },
      {
         "postcode":3260,
         "state":"VIC",
         "vicSuburb":"SKIBO"
      },
      {
         "postcode":3181,
         "state":"VIC",
         "vicSuburb":"PRAHRAN EAST"
      },
      {
         "postcode":3285,
         "state":"VIC",
         "vicSuburb":"ST HELENS"
      },
      {
         "postcode":3233,
         "state":"VIC",
         "vicSuburb":"SKENES CREEK NORTH"
      },
      {
         "postcode":3271,
         "state":"VIC",
         "vicSuburb":"DARLINGTON"
      },
      {
         "postcode":3121,
         "state":"VIC",
         "vicSuburb":"RICHMOND"
      },
      {
         "postcode":3268,
         "state":"VIC",
         "vicSuburb":"TIMBOON WEST"
      },
      {
         "postcode":3268,
         "state":"VIC",
         "vicSuburb":"TIMBOON"
      },
      {
         "postcode":3167,
         "state":"VIC",
         "vicSuburb":"OAKLEIGH SOUTH"
      },
      {
         "postcode":3084,
         "state":"VIC",
         "vicSuburb":"BANYULE"
      },
      {
         "postcode":3130,
         "state":"VIC",
         "vicSuburb":"BLACKBURN"
      },
      {
         "postcode":3216,
         "state":"VIC",
         "vicSuburb":"GROVEDALE"
      },
      {
         "postcode":3215,
         "state":"VIC",
         "vicSuburb":"DRUMCONDRA"
      },
      {
         "postcode":3251,
         "state":"VIC",
         "vicSuburb":"EURACK"
      },
      {
         "postcode":3021,
         "state":"VIC",
         "vicSuburb":"KEALBA"
      },
      {
         "postcode":3175,
         "state":"VIC",
         "vicSuburb":"BANGHOLME"
      },
      {
         "postcode":3186,
         "state":"VIC",
         "vicSuburb":"BRIGHTON"
      },
      {
         "postcode":3286,
         "state":"VIC",
         "vicSuburb":"KNEBSWORTH"
      },
      {
         "postcode":3124,
         "state":"VIC",
         "vicSuburb":"HARTWELL"
      },
      {
         "postcode":3283,
         "state":"VIC",
         "vicSuburb":"TARRONE"
      },
      {
         "postcode":3046,
         "state":"VIC",
         "vicSuburb":"HADFIELD"
      },
      {
         "postcode":3070,
         "state":"VIC",
         "vicSuburb":"NORTHCOTE SOUTH"
      },
      {
         "postcode":3076,
         "state":"VIC",
         "vicSuburb":"EPPING"
      },
      {
         "postcode":3087,
         "state":"VIC",
         "vicSuburb":"WATSONIA NORTH"
      },
      {
         "postcode":3016,
         "state":"VIC",
         "vicSuburb":"WILLIAMSTOWN NORTH"
      },
      {
         "postcode":3178,
         "state":"VIC",
         "vicSuburb":"ROWVILLE"
      },
      {
         "postcode":3013,
         "state":"VIC",
         "vicSuburb":"YARRAVILLE WEST"
      },
      {
         "postcode":3240,
         "state":"VIC",
         "vicSuburb":"MODEWARRE"
      },
      {
         "postcode":3113,
         "state":"VIC",
         "vicSuburb":"NORTH WARRANDYTE"
      },
      {
         "postcode":3074,
         "state":"VIC",
         "vicSuburb":"THOMASTOWN"
      },
      {
         "postcode":3181,
         "state":"VIC",
         "vicSuburb":"WINDSOR"
      },
      {
         "postcode":3152,
         "state":"VIC",
         "vicSuburb":"WANTIRNA SOUTH"
      },
      {
         "postcode":3025,
         "state":"VIC",
         "vicSuburb":"ALTONA EAST"
      },
      {
         "postcode":3149,
         "state":"VIC",
         "vicSuburb":"MOUNT WAVERLEY"
      },
      {
         "postcode":3225,
         "state":"VIC",
         "vicSuburb":"QUEENSCLIFF"
      },
      {
         "postcode":3139,
         "state":"VIC",
         "vicSuburb":"LAUNCHING PLACE"
      },
      {
         "postcode":3235,
         "state":"VIC",
         "vicSuburb":"BOONAH"
      },
      {
         "postcode":3277,
         "state":"VIC",
         "vicSuburb":"MEPUNGA"
      },
      {
         "postcode":3032,
         "state":"VIC",
         "vicSuburb":"HIGHPOINT CITY"
      },
      {
         "postcode":3046,
         "state":"VIC",
         "vicSuburb":"OAK PARK"
      },
      {
         "postcode":3113,
         "state":"VIC",
         "vicSuburb":"WARRANDYTE"
      },
      {
         "postcode":3068,
         "state":"VIC",
         "vicSuburb":"CLIFTON HILL"
      },
      {
         "postcode":3058,
         "state":"VIC",
         "vicSuburb":"COBURG"
      },
      {
         "postcode":3148,
         "state":"VIC",
         "vicSuburb":"HOLMESGLEN"
      },
      {
         "postcode":3058,
         "state":"VIC",
         "vicSuburb":"MORELAND"
      },
      {
         "postcode":3158,
         "state":"VIC",
         "vicSuburb":"UPWEY"
      },
      {
         "postcode":3123,
         "state":"VIC",
         "vicSuburb":"HAWTHORN EAST"
      },
      {
         "postcode":3181,
         "state":"VIC",
         "vicSuburb":"PRAHRAN"
      },
      {
         "postcode":3196,
         "state":"VIC",
         "vicSuburb":"EDITHVALE"
      },
      {
         "postcode":3200,
         "state":"VIC",
         "vicSuburb":"PINES FOREST"
      },
      {
         "postcode":3216,
         "state":"VIC",
         "vicSuburb":"WANDANA HEIGHTS"
      },
      {
         "postcode":3237,
         "state":"VIC",
         "vicSuburb":"WATTLE HILL"
      },
      {
         "postcode":3040,
         "state":"VIC",
         "vicSuburb":"ESSENDON WEST"
      },
      {
         "postcode":3101,
         "state":"VIC",
         "vicSuburb":"COTHAM"
      },
      {
         "postcode":3174,
         "state":"VIC",
         "vicSuburb":"NOBLE PARK"
      },
      {
         "postcode":3095,
         "state":"VIC",
         "vicSuburb":"RESEARCH"
      },
      {
         "postcode":3268,
         "state":"VIC",
         "vicSuburb":"NULLAWARRE"
      },
      {
         "postcode":3124,
         "state":"VIC",
         "vicSuburb":"CAMBERWELL WEST"
      },
      {
         "postcode":3047,
         "state":"VIC",
         "vicSuburb":"BROADMEADOWS"
      },
      {
         "postcode":3103,
         "state":"VIC",
         "vicSuburb":"BALWYN"
      },
      {
         "postcode":3221,
         "state":"VIC",
         "vicSuburb":"GNARWARRE"
      },
      {
         "postcode":3243,
         "state":"VIC",
         "vicSuburb":"WARNCOORT"
      },
      {
         "postcode":3294,
         "state":"VIC",
         "vicSuburb":"MOUTAJUP"
      },
      {
         "postcode":3272,
         "state":"VIC",
         "vicSuburb":"MORTLAKE"
      },
      {
         "postcode":3060,
         "state":"VIC",
         "vicSuburb":"FAWKNER"
      },
      {
         "postcode":3216,
         "state":"VIC",
         "vicSuburb":"BELMONT"
      },
      {
         "postcode":3268,
         "state":"VIC",
         "vicSuburb":"CURDIES RIVER"
      },
      {
         "postcode":3272,
         "state":"VIC",
         "vicSuburb":"WOORNDOO"
      },
      {
         "postcode":3129,
         "state":"VIC",
         "vicSuburb":"KERRIMUIR"
      },
      {
         "postcode":3284,
         "state":"VIC",
         "vicSuburb":"PORT FAIRY"
      },
      {
         "postcode":3249,
         "state":"VIC",
         "vicSuburb":"PIRRON YALLOCK"
      },
      {
         "postcode":3062,
         "state":"VIC",
         "vicSuburb":"SOMERTON"
      },
      {
         "postcode":3053,
         "state":"VIC",
         "vicSuburb":"CARLTON"
      },
      {
         "postcode":3294,
         "state":"VIC",
         "vicSuburb":"VICTORIA VALLEY"
      },
      {
         "postcode":3032,
         "state":"VIC",
         "vicSuburb":"MARIBYRNONG"
      },
      {
         "postcode":3128,
         "state":"VIC",
         "vicSuburb":"BOX HILL CENTRAL"
      },
      {
         "postcode":3175,
         "state":"VIC",
         "vicSuburb":"DANDENONG"
      },
      {
         "postcode":3192,
         "state":"VIC",
         "vicSuburb":"SOUTHLAND CENTRE"
      },
      {
         "postcode":3237,
         "state":"VIC",
         "vicSuburb":"BEECH FOREST"
      },
      {
         "postcode":3260,
         "state":"VIC",
         "vicSuburb":"BOOKAAR"
      },
      {
         "postcode":3012,
         "state":"VIC",
         "vicSuburb":"TOTTENHAM"
      },
      {
         "postcode":3235,
         "state":"VIC",
         "vicSuburb":"DEANS MARSH"
      },
      {
         "postcode":3221,
         "state":"VIC",
         "vicSuburb":"BELLARINE"
      },
      {
         "postcode":3199,
         "state":"VIC",
         "vicSuburb":"FRANKSTON"
      },
      {
         "postcode":3127,
         "state":"VIC",
         "vicSuburb":"SURREY HILLS NORTH"
      },
      {
         "postcode":3040,
         "state":"VIC",
         "vicSuburb":"ABERFELDIE"
      },
      {
         "postcode":3072,
         "state":"VIC",
         "vicSuburb":"PRESTON"
      },
      {
         "postcode":3075,
         "state":"VIC",
         "vicSuburb":"LALOR"
      },
      {
         "postcode":3137,
         "state":"VIC",
         "vicSuburb":"KILSYTH SOUTH"
      },
      {
         "postcode":3182,
         "state":"VIC",
         "vicSuburb":"ST KILDA WEST"
      },
      {
         "postcode":3011,
         "state":"VIC",
         "vicSuburb":"SEDDON WEST"
      },
      {
         "postcode":3218,
         "state":"VIC",
         "vicSuburb":"GEELONG WEST"
      },
      {
         "postcode":3249,
         "state":"VIC",
         "vicSuburb":"CORUNNUN"
      },
      {
         "postcode":3012,
         "state":"VIC",
         "vicSuburb":"MAIDSTONE"
      },
      {
         "postcode":3230,
         "state":"VIC",
         "vicSuburb":"ANGLESEA"
      },
      {
         "postcode":3241,
         "state":"VIC",
         "vicSuburb":"OMBERSLEY"
      },
      {
         "postcode":3192,
         "state":"VIC",
         "vicSuburb":"CHELTENHAM NORTH"
      },
      {
         "postcode":3265,
         "state":"VIC",
         "vicSuburb":"LAANG"
      },
      {
         "postcode":3292,
         "state":"VIC",
         "vicSuburb":"NELSON"
      },
      {
         "postcode":3219,
         "state":"VIC",
         "vicSuburb":"NEWCOMB"
      },
      {
         "postcode":3161,
         "state":"VIC",
         "vicSuburb":"CAULFIELD NORTH"
      },
      {
         "postcode":3266,
         "state":"VIC",
         "vicSuburb":"JANCOURT EAST"
      },
      {
         "postcode":3200,
         "state":"VIC",
         "vicSuburb":"FRANKSTON NORTH"
      },
      {
         "postcode":3161,
         "state":"VIC",
         "vicSuburb":"CAULFIELD JUNCTION"
      },
      {
         "postcode":3293,
         "state":"VIC",
         "vicSuburb":"NAREEB"
      },
      {
         "postcode":3109,
         "state":"VIC",
         "vicSuburb":"DONCASTER HEIGHTS"
      },
      {
         "postcode":3165,
         "state":"VIC",
         "vicSuburb":"BENTLEIGH EAST"
      },
      {
         "postcode":3182,
         "state":"VIC",
         "vicSuburb":"ST KILDA"
      },
      {
         "postcode":3099,
         "state":"VIC",
         "vicSuburb":"COTTLES BRIDGE"
      },
      {
         "postcode":3073,
         "state":"VIC",
         "vicSuburb":"RESERVOIR EAST"
      },
      {
         "postcode":3239,
         "state":"VIC",
         "vicSuburb":"KENNEDYS CREEK"
      },
      {
         "postcode":3249,
         "state":"VIC",
         "vicSuburb":"YEO"
      },
      {
         "postcode":3280,
         "state":"VIC",
         "vicSuburb":"WARRNAMBOOL WEST"
      },
      {
         "postcode":3190,
         "state":"VIC",
         "vicSuburb":"HIGHETT"
      },
      {
         "postcode":3030,
         "state":"VIC",
         "vicSuburb":"WERRIBEE"
      },
      {
         "postcode":3101,
         "state":"VIC",
         "vicSuburb":"KEW"
      },
      {
         "postcode":3219,
         "state":"VIC",
         "vicSuburb":"EAST GEELONG"
      },
      {
         "postcode":3276,
         "state":"VIC",
         "vicSuburb":"MINJAH"
      },
      {
         "postcode":3114,
         "state":"VIC",
         "vicSuburb":"PARK ORCHARDS"
      },
      {
         "postcode":3240,
         "state":"VIC",
         "vicSuburb":"MOUNT MORIAC"
      },
      {
         "postcode":3039,
         "state":"VIC",
         "vicSuburb":"MOONEE PONDS"
      },
      {
         "postcode":3215,
         "state":"VIC",
         "vicSuburb":"HAMLYN HEIGHTS"
      },
      {
         "postcode":3174,
         "state":"VIC",
         "vicSuburb":"NOBLE PARK NORTH"
      },
      {
         "postcode":3041,
         "state":"VIC",
         "vicSuburb":"STRATHMORE HEIGHTS"
      },
      {
         "postcode":3184,
         "state":"VIC",
         "vicSuburb":"ELWOOD"
      },
      {
         "postcode":3196,
         "state":"VIC",
         "vicSuburb":"BONBEACH"
      },
      {
         "postcode":3058,
         "state":"VIC",
         "vicSuburb":"COBURG NORTH"
      },
      {
         "postcode":3165,
         "state":"VIC",
         "vicSuburb":"COATESVILLE"
      },
      {
         "postcode":3000,
         "state":"VIC",
         "vicSuburb":"MELBOURNE"
      },
      {
         "postcode":3250,
         "state":"VIC",
         "vicSuburb":"COLAC WEST"
      },
      {
         "postcode":3250,
         "state":"VIC",
         "vicSuburb":"COLAC"
      },
      {
         "postcode":3141,
         "state":"VIC",
         "vicSuburb":"CHAPEL STREET NORTH"
      },
      {
         "postcode":3199,
         "state":"VIC",
         "vicSuburb":"KARINGAL CENTRE"
      },
      {
         "postcode":3249,
         "state":"VIC",
         "vicSuburb":"LARPENT"
      },
      {
         "postcode":3249,
         "state":"VIC",
         "vicSuburb":"BALINTORE"
      },
      {
         "postcode":3266,
         "state":"VIC",
         "vicSuburb":"BULLAHARRE"
      },
      {
         "postcode":3052,
         "state":"VIC",
         "vicSuburb":"MELBOURNE UNIVERSITY"
      },
      {
         "postcode":3285,
         "state":"VIC",
         "vicSuburb":"TYRENDARRA EAST"
      },
      {
         "postcode":3163,
         "state":"VIC",
         "vicSuburb":"CARNEGIE"
      },
      {
         "postcode":3011,
         "state":"VIC",
         "vicSuburb":"SEDDON"
      },
      {
         "postcode":3082,
         "state":"VIC",
         "vicSuburb":"MILL PARK"
      },
      {
         "postcode":3260,
         "state":"VIC",
         "vicSuburb":"SOUTH PURRUMBETE"
      },
      {
         "postcode":3265,
         "state":"VIC",
         "vicSuburb":"GLENORMISTON NORTH"
      },
      {
         "postcode":3027,
         "state":"VIC",
         "vicSuburb":"LAVERTON RAAF"
      },
      {
         "postcode":3043,
         "state":"VIC",
         "vicSuburb":"GLADSTONE PARK"
      },
      {
         "postcode":3057,
         "state":"VIC",
         "vicSuburb":"BRUNSWICK EAST"
      },
      {
         "postcode":3268,
         "state":"VIC",
         "vicSuburb":"HEYTESBURY LOWER"
      },
      {
         "postcode":3192,
         "state":"VIC",
         "vicSuburb":"CHELTENHAM"
      },
      {
         "postcode":3283,
         "state":"VIC",
         "vicSuburb":"TOWER HILL"
      },
      {
         "postcode":3268,
         "state":"VIC",
         "vicSuburb":"BRUCKNELL"
      },
      {
         "postcode":3129,
         "state":"VIC",
         "vicSuburb":"BOX HILL NORTH"
      },
      {
         "postcode":3280,
         "state":"VIC",
         "vicSuburb":"WARRNAMBOOL"
      },
      {
         "postcode":3061,
         "state":"VIC",
         "vicSuburb":"CAMPBELLFIELD"
      },
      {
         "postcode":3122,
         "state":"VIC",
         "vicSuburb":"HAWTHORN WEST"
      },
      {
         "postcode":3139,
         "state":"VIC",
         "vicSuburb":"SEVILLE EAST"
      },
      {
         "postcode":3281,
         "state":"VIC",
         "vicSuburb":"WOODFORD"
      },
      {
         "postcode":3081,
         "state":"VIC",
         "vicSuburb":"HEIDELBERG HEIGHTS"
      },
      {
         "postcode":3175,
         "state":"VIC",
         "vicSuburb":"DUNEARN"
      },
      {
         "postcode":3287,
         "state":"VIC",
         "vicSuburb":"HAWKESDALE"
      },
      {
         "postcode":3123,
         "state":"VIC",
         "vicSuburb":"AUBURN"
      },
      {
         "postcode":3136,
         "state":"VIC",
         "vicSuburb":"CROYDON SOUTH"
      },
      {
         "postcode":3166,
         "state":"VIC",
         "vicSuburb":"HUGHESDALE"
      },
      {
         "postcode":3195,
         "state":"VIC",
         "vicSuburb":"MORDIALLOC"
      },
      {
         "postcode":3081,
         "state":"VIC",
         "vicSuburb":"HEIDELBERG WEST"
      },
      {
         "postcode":3221,
         "state":"VIC",
         "vicSuburb":"WONGARRA"
      },
      {
         "postcode":3249,
         "state":"VIC",
         "vicSuburb":"BARRAMUNGA"
      },
      {
         "postcode":3238,
         "state":"VIC",
         "vicSuburb":"JOHANNA"
      },
      {
         "postcode":3265,
         "state":"VIC",
         "vicSuburb":"NOORAT EAST"
      },
      {
         "postcode":3019,
         "state":"VIC",
         "vicSuburb":"ROBINSON"
      },
      {
         "postcode":3249,
         "state":"VIC",
         "vicSuburb":"ALVIE"
      },
      {
         "postcode":3097,
         "state":"VIC",
         "vicSuburb":"BEND OF ISLANDS"
      },
      {
         "postcode":3121,
         "state":"VIC",
         "vicSuburb":"RICHMOND EAST"
      },
      {
         "postcode":3283,
         "state":"VIC",
         "vicSuburb":"WILLATOOK"
      },
      {
         "postcode":3145,
         "state":"VIC",
         "vicSuburb":"DARLING"
      },
      {
         "postcode":3135,
         "state":"VIC",
         "vicSuburb":"RINGWOOD EAST"
      },
      {
         "postcode":3020,
         "state":"VIC",
         "vicSuburb":"SUNSHINE NORTH"
      },
      {
         "postcode":3201,
         "state":"VIC",
         "vicSuburb":"CARRUM DOWNS"
      },
      {
         "postcode":3134,
         "state":"VIC",
         "vicSuburb":"RINGWOOD"
      },
      {
         "postcode":3050,
         "state":"VIC",
         "vicSuburb":"ROYAL MELBOURNE HOSPITAL"
      },
      {
         "postcode":3125,
         "state":"VIC",
         "vicSuburb":"SURREY HILLS SOUTH"
      },
      {
         "postcode":3142,
         "state":"VIC",
         "vicSuburb":"HAWKSBURN"
      },
      {
         "postcode":3293,
         "state":"VIC",
         "vicSuburb":"NARRAPUMELAP SOUTH"
      },
      {
         "postcode":3225,
         "state":"VIC",
         "vicSuburb":"POINT LONSDALE"
      },
      {
         "postcode":3041,
         "state":"VIC",
         "vicSuburb":"STRATHMORE"
      },
      {
         "postcode":3185,
         "state":"VIC",
         "vicSuburb":"GARDENVALE"
      },
      {
         "postcode":3221,
         "state":"VIC",
         "vicSuburb":"GREY RIVER"
      },
      {
         "postcode":3249,
         "state":"VIC",
         "vicSuburb":"IRREWILLIPE EAST"
      },
      {
         "postcode":3139,
         "state":"VIC",
         "vicSuburb":"SEVILLE"
      },
      {
         "postcode":3249,
         "state":"VIC",
         "vicSuburb":"POMBORNEIT EAST"
      },
      {
         "postcode":3265,
         "state":"VIC",
         "vicSuburb":"ECKLIN SOUTH"
      },
      {
         "postcode":3056,
         "state":"VIC",
         "vicSuburb":"BRUNSWICK NORTH"
      },
      {
         "postcode":3221,
         "state":"VIC",
         "vicSuburb":"BARRABOOL"
      },
      {
         "postcode":3265,
         "state":"VIC",
         "vicSuburb":"NOORAT"
      },
      {
         "postcode":3095,
         "state":"VIC",
         "vicSuburb":"ELTHAM"
      },
      {
         "postcode":3226,
         "state":"VIC",
         "vicSuburb":"OCEAN GROVE"
      },
      {
         "postcode":3085,
         "state":"VIC",
         "vicSuburb":"MACLEOD WEST"
      },
      {
         "postcode":3294,
         "state":"VIC",
         "vicSuburb":"DUNKELD"
      },
      {
         "postcode":3047,
         "state":"VIC",
         "vicSuburb":"DALLAS"
      },
      {
         "postcode":3260,
         "state":"VIC",
         "vicSuburb":"POMBORNEIT NORTH"
      },
      {
         "postcode":3055,
         "state":"VIC",
         "vicSuburb":"MORELAND WEST"
      },
      {
         "postcode":3231,
         "state":"VIC",
         "vicSuburb":"EASTERN VIEW"
      },
      {
         "postcode":3022,
         "state":"VIC",
         "vicSuburb":"ARDEER"
      },
      {
         "postcode":3021,
         "state":"VIC",
         "vicSuburb":"ALBANVALE"
      },
      {
         "postcode":3088,
         "state":"VIC",
         "vicSuburb":"GREENSBOROUGH"
      },
      {
         "postcode":3186,
         "state":"VIC",
         "vicSuburb":"DENDY"
      },
      {
         "postcode":3036,
         "state":"VIC",
         "vicSuburb":"KEILOR NORTH"
      },
      {
         "postcode":3266,
         "state":"VIC",
         "vicSuburb":"COBDEN"
      },
      {
         "postcode":3285,
         "state":"VIC",
         "vicSuburb":"TYRENDARRA"
      },
      {
         "postcode":3277,
         "state":"VIC",
         "vicSuburb":"MEPUNGA WEST"
      },
      {
         "postcode":3072,
         "state":"VIC",
         "vicSuburb":"PRESTON SOUTH"
      },
      {
         "postcode":3111,
         "state":"VIC",
         "vicSuburb":"DONVALE"
      },
      {
         "postcode":3128,
         "state":"VIC",
         "vicSuburb":"WATTLE PARK"
      },
      {
         "postcode":3238,
         "state":"VIC",
         "vicSuburb":"GLENAIRE"
      },
      {
         "postcode":3199,
         "state":"VIC",
         "vicSuburb":"KARINGAL"
      },
      {
         "postcode":3006,
         "state":"VIC",
         "vicSuburb":"SOUTHBANK"
      },
      {
         "postcode":3249,
         "state":"VIC",
         "vicSuburb":"BARONGAROOK"
      },
      {
         "postcode":3289,
         "state":"VIC",
         "vicSuburb":"TABOR"
      },
      {
         "postcode":3277,
         "state":"VIC",
         "vicSuburb":"ALLANSFORD"
      },
      {
         "postcode":3283,
         "state":"VIC",
         "vicSuburb":"KIRKSTALL"
      },
      {
         "postcode":3125,
         "state":"VIC",
         "vicSuburb":"BURWOOD"
      },
      {
         "postcode":3221,
         "state":"VIC",
         "vicSuburb":"MOOLAP"
      },
      {
         "postcode":3172,
         "state":"VIC",
         "vicSuburb":"DINGLEY VILLAGE"
      },
      {
         "postcode":3237,
         "state":"VIC",
         "vicSuburb":"WYELANGTA"
      },
      {
         "postcode":3058,
         "state":"VIC",
         "vicSuburb":"BATMAN"
      },
      {
         "postcode":3038,
         "state":"VIC",
         "vicSuburb":"KEILOR DOWNS"
      },
      {
         "postcode":3064,
         "state":"VIC",
         "vicSuburb":"MICKLEHAM"
      },
      {
         "postcode":3280,
         "state":"VIC",
         "vicSuburb":"DENNINGTON"
      },
      {
         "postcode":3220,
         "state":"VIC",
         "vicSuburb":"BAREENA"
      },
      {
         "postcode":3156,
         "state":"VIC",
         "vicSuburb":"UPPER FERNTREE GULLY"
      },
      {
         "postcode":3265,
         "state":"VIC",
         "vicSuburb":"GLENORMISTON SOUTH"
      },
      {
         "postcode":3216,
         "state":"VIC",
         "vicSuburb":"HIGHTON"
      },
      {
         "postcode":3141,
         "state":"VIC",
         "vicSuburb":"SOUTH YARRA"
      },
      {
         "postcode":3177,
         "state":"VIC",
         "vicSuburb":"DOVETON"
      },
      {
         "postcode":3221,
         "state":"VIC",
         "vicSuburb":"FYANSFORD"
      },
      {
         "postcode":3195,
         "state":"VIC",
         "vicSuburb":"ASPENDALE"
      },
      {
         "postcode":3070,
         "state":"VIC",
         "vicSuburb":"NORTHCOTE"
      },
      {
         "postcode":3134,
         "state":"VIC",
         "vicSuburb":"WARRANDYTE SOUTH"
      },
      {
         "postcode":3163,
         "state":"VIC",
         "vicSuburb":"MURRUMBEENA"
      },
      {
         "postcode":3232,
         "state":"VIC",
         "vicSuburb":"LORNE"
      },
      {
         "postcode":3289,
         "state":"VIC",
         "vicSuburb":"GERRIGERRUP"
      },
      {
         "postcode":3266,
         "state":"VIC",
         "vicSuburb":"COBRICO"
      },
      {
         "postcode":3150,
         "state":"VIC",
         "vicSuburb":"GLEN WAVERLEY"
      },
      {
         "postcode":3221,
         "state":"VIC",
         "vicSuburb":"SEPARATION CREEK"
      },
      {
         "postcode":3233,
         "state":"VIC",
         "vicSuburb":"PETTICOAT CREEK"
      },
      {
         "postcode":3130,
         "state":"VIC",
         "vicSuburb":"BLACKBURN NORTH"
      },
      {
         "postcode":3249,
         "state":"VIC",
         "vicSuburb":"YEODENE"
      },
      {
         "postcode":3279,
         "state":"VIC",
         "vicSuburb":"BALLANGEICH"
      },
      {
         "postcode":3160,
         "state":"VIC",
         "vicSuburb":"TECOMA"
      },
      {
         "postcode":3266,
         "state":"VIC",
         "vicSuburb":"ELINGAMITE"
      },
      {
         "postcode":3286,
         "state":"VIC",
         "vicSuburb":"CONDAH SWAMP"
      },
      {
         "postcode":3122,
         "state":"VIC",
         "vicSuburb":"AUBURN SOUTH"
      },
      {
         "postcode":3250,
         "state":"VIC",
         "vicSuburb":"COLAC EAST"
      },
      {
         "postcode":3012,
         "state":"VIC",
         "vicSuburb":"KINGSVILLE WEST"
      },
      {
         "postcode":3029,
         "state":"VIC",
         "vicSuburb":"TRUGANINA"
      },
      {
         "postcode":3195,
         "state":"VIC",
         "vicSuburb":"PARKDALE"
      },
      {
         "postcode":3065,
         "state":"VIC",
         "vicSuburb":"FITZROY"
      },
      {
         "postcode":3037,
         "state":"VIC",
         "vicSuburb":"TAYLORS HILL"
      },
      {
         "postcode":3030,
         "state":"VIC",
         "vicSuburb":"WERRIBEE SOUTH"
      },
      {
         "postcode":3072,
         "state":"VIC",
         "vicSuburb":"PRESTON LOWER"
      },
      {
         "postcode":3146,
         "state":"VIC",
         "vicSuburb":"GLEN IRIS"
      },
      {
         "postcode":3286,
         "state":"VIC",
         "vicSuburb":"MACARTHUR"
      },
      {
         "postcode":3241,
         "state":"VIC",
         "vicSuburb":"WENSLEYDALE"
      },
      {
         "postcode":3124,
         "state":"VIC",
         "vicSuburb":"CAMBERWELL NORTH"
      },
      {
         "postcode":3215,
         "state":"VIC",
         "vicSuburb":"RIPPLESIDE"
      },
      {
         "postcode":3132,
         "state":"VIC",
         "vicSuburb":"MITCHAM NORTH"
      },
      {
         "postcode":3139,
         "state":"VIC",
         "vicSuburb":"WOORI YALLOCK"
      },
      {
         "postcode":3140,
         "state":"VIC",
         "vicSuburb":"LILYDALE"
      },
      {
         "postcode":3211,
         "state":"VIC",
         "vicSuburb":"LITTLE RIVER"
      },
      {
         "postcode":3265,
         "state":"VIC",
         "vicSuburb":"DIXIE"
      },
      {
         "postcode":3139,
         "state":"VIC",
         "vicSuburb":"WANDIN EAST"
      },
      {
         "postcode":3179,
         "state":"VIC",
         "vicSuburb":"SCORESBY"
      },
      {
         "postcode":3003,
         "state":"VIC",
         "vicSuburb":"WEST MELBOURNE"
      },
      {
         "postcode":3153,
         "state":"VIC",
         "vicSuburb":"BAYSWATER"
      },
      {
         "postcode":3028,
         "state":"VIC",
         "vicSuburb":"LAVERTON"
      },
      {
         "postcode":3015,
         "state":"VIC",
         "vicSuburb":"SOUTH KINGSVILLE"
      },
      {
         "postcode":3067,
         "state":"VIC",
         "vicSuburb":"ABBOTSFORD"
      },
      {
         "postcode":3202,
         "state":"VIC",
         "vicSuburb":"HEATHERTON"
      },
      {
         "postcode":3023,
         "state":"VIC",
         "vicSuburb":"CAIRNLEA"
      },
      {
         "postcode":3047,
         "state":"VIC",
         "vicSuburb":"JACANA"
      },
      {
         "postcode":3294,
         "state":"VIC",
         "vicSuburb":"KARABEAL"
      },
      {
         "postcode":3265,
         "state":"VIC",
         "vicSuburb":"KOLORA"
      },
      {
         "postcode":3147,
         "state":"VIC",
         "vicSuburb":"ASHWOOD"
      },
      {
         "postcode":3099,
         "state":"VIC",
         "vicSuburb":"ARTHURS CREEK"
      },
      {
         "postcode":3216,
         "state":"VIC",
         "vicSuburb":"MOUNT DUNEED"
      },
      {
         "postcode":3285,
         "state":"VIC",
         "vicSuburb":"NARRAWONG"
      },
      {
         "postcode":3172,
         "state":"VIC",
         "vicSuburb":"SPRINGVALE SOUTH"
      },
      {
         "postcode":3173,
         "state":"VIC",
         "vicSuburb":"KEYSBOROUGH"
      },
      {
         "postcode":3084,
         "state":"VIC",
         "vicSuburb":"ROSANNA"
      },
      {
         "postcode":3280,
         "state":"VIC",
         "vicSuburb":"WARRNAMBOOL EAST"
      },
      {
         "postcode":3149,
         "state":"VIC",
         "vicSuburb":"SYNDAL"
      },
      {
         "postcode":3269,
         "state":"VIC",
         "vicSuburb":"WAARRE"
      },
      {
         "postcode":3096,
         "state":"VIC",
         "vicSuburb":"WATTLE GLEN"
      },
      {
         "postcode":3287,
         "state":"VIC",
         "vicSuburb":"MINHAMITE"
      },
      {
         "postcode":3194,
         "state":"VIC",
         "vicSuburb":"MENTONE"
      },
      {
         "postcode":3078,
         "state":"VIC",
         "vicSuburb":"ALPHINGTON"
      },
      {
         "postcode":3275,
         "state":"VIC",
         "vicSuburb":"MAILORS FLAT"
      },
      {
         "postcode":3023,
         "state":"VIC",
         "vicSuburb":"CAROLINE SPRINGS"
      },
      {
         "postcode":3155,
         "state":"VIC",
         "vicSuburb":"BORONIA"
      },
      {
         "postcode":3024,
         "state":"VIC",
         "vicSuburb":"MOUNT COTTRELL"
      },
      {
         "postcode":3124,
         "state":"VIC",
         "vicSuburb":"CAMBERWELL SOUTH"
      },
      {
         "postcode":3054,
         "state":"VIC",
         "vicSuburb":"CARLTON NORTH"
      },
      {
         "postcode":3104,
         "state":"VIC",
         "vicSuburb":"BALWYN NORTH"
      },
      {
         "postcode":3180,
         "state":"VIC",
         "vicSuburb":"KNOXFIELD"
      },
      {
         "postcode":3268,
         "state":"VIC",
         "vicSuburb":"COWLEYS CREEK"
      },
      {
         "postcode":3235,
         "state":"VIC",
         "vicSuburb":"BENWERRIN"
      },
      {
         "postcode":3184,
         "state":"VIC",
         "vicSuburb":"BRIGHTON ROAD"
      },
      {
         "postcode":3268,
         "state":"VIC",
         "vicSuburb":"THE COVE"
      },
      {
         "postcode":3249,
         "state":"VIC",
         "vicSuburb":"IRREWILLIPE"
      },
      {
         "postcode":3159,
         "state":"VIC",
         "vicSuburb":"MENZIES CREEK"
      },
      {
         "postcode":3266,
         "state":"VIC",
         "vicSuburb":"GLENFYNE"
      },
      {
         "postcode":3055,
         "state":"VIC",
         "vicSuburb":"MOONEE VALE"
      },
      {
         "postcode":3166,
         "state":"VIC",
         "vicSuburb":"OAKLEIGH"
      },
      {
         "postcode":3012,
         "state":"VIC",
         "vicSuburb":"WEST FOOTSCRAY"
      },
      {
         "postcode":3134,
         "state":"VIC",
         "vicSuburb":"RINGWOOD NORTH"
      },
      {
         "postcode":3240,
         "state":"VIC",
         "vicSuburb":"BUCKLEY"
      },
      {
         "postcode":3286,
         "state":"VIC",
         "vicSuburb":"WARRABKOOK"
      },
      {
         "postcode":3044,
         "state":"VIC",
         "vicSuburb":"PASCOE VALE"
      },
      {
         "postcode":3126,
         "state":"VIC",
         "vicSuburb":"CANTERBURY"
      },
      {
         "postcode":3020,
         "state":"VIC",
         "vicSuburb":"GLENGALA"
      },
      {
         "postcode":3214,
         "state":"VIC",
         "vicSuburb":"NORLANE"
      },
      {
         "postcode":3251,
         "state":"VIC",
         "vicSuburb":"WEERING"
      },
      {
         "postcode":3294,
         "state":"VIC",
         "vicSuburb":"MIRRANATWA"
      },
      {
         "postcode":3083,
         "state":"VIC",
         "vicSuburb":"KINGSBURY"
      },
      {
         "postcode":3097,
         "state":"VIC",
         "vicSuburb":"WATSONS CREEK"
      },
      {
         "postcode":3265,
         "state":"VIC",
         "vicSuburb":"GARVOC"
      },
      {
         "postcode":3020,
         "state":"VIC",
         "vicSuburb":"ALBION"
      },
      {
         "postcode":3228,
         "state":"VIC",
         "vicSuburb":"JAN JUC"
      },
      {
         "postcode":3224,
         "state":"VIC",
         "vicSuburb":"LEOPOLD"
      },
      {
         "postcode":3219,
         "state":"VIC",
         "vicSuburb":"ST ALBANS PARK"
      },
      {
         "postcode":3237,
         "state":"VIC",
         "vicSuburb":"AIRE VALLEY"
      },
      {
         "postcode":3015,
         "state":"VIC",
         "vicSuburb":"SPOTSWOOD"
      },
      {
         "postcode":3196,
         "state":"VIC",
         "vicSuburb":"CHELSEA"
      },
      {
         "postcode":3166,
         "state":"VIC",
         "vicSuburb":"HUNTINGDALE"
      },
      {
         "postcode":3041,
         "state":"VIC",
         "vicSuburb":"ESSENDON NORTH"
      },
      {
         "postcode":3197,
         "state":"VIC",
         "vicSuburb":"PATTERSON LAKES"
      },
      {
         "postcode":3277,
         "state":"VIC",
         "vicSuburb":"MEPUNGA EAST"
      },
      {
         "postcode":3260,
         "state":"VIC",
         "vicSuburb":"CAMPERDOWN"
      },
      {
         "postcode":3293,
         "state":"VIC",
         "vicSuburb":"GLENTHOMPSON"
      },
      {
         "postcode":3268,
         "state":"VIC",
         "vicSuburb":"PAARATTE"
      },
      {
         "postcode":3265,
         "state":"VIC",
         "vicSuburb":"PANMURE"
      },
      {
         "postcode":3265,
         "state":"VIC",
         "vicSuburb":"ELLERSLIE"
      },
      {
         "postcode":3030,
         "state":"VIC",
         "vicSuburb":"DERRIMUT"
      },
      {
         "postcode":3137,
         "state":"VIC",
         "vicSuburb":"KILSYTH"
      },
      {
         "postcode":3175,
         "state":"VIC",
         "vicSuburb":"DANDENONG SOUTH"
      },
      {
         "postcode":3221,
         "state":"VIC",
         "vicSuburb":"STONEHAVEN"
      },
      {
         "postcode":3043,
         "state":"VIC",
         "vicSuburb":"TULLAMARINE"
      },
      {
         "postcode":3023,
         "state":"VIC",
         "vicSuburb":"RAVENHALL"
      },
      {
         "postcode":3249,
         "state":"VIC",
         "vicSuburb":"NALANGIL"
      },
      {
         "postcode":3025,
         "state":"VIC",
         "vicSuburb":"ALTONA NORTH"
      },
      {
         "postcode":3023,
         "state":"VIC",
         "vicSuburb":"DEER PARK NORTH"
      },
      {
         "postcode":3122,
         "state":"VIC",
         "vicSuburb":"HAWTHORN"
      },
      {
         "postcode":3162,
         "state":"VIC",
         "vicSuburb":"CAULFIELD SOUTH"
      },
      {
         "postcode":3166,
         "state":"VIC",
         "vicSuburb":"OAKLEIGH EAST"
      },
      {
         "postcode":3170,
         "state":"VIC",
         "vicSuburb":"MULGRAVE"
      },
      {
         "postcode":3030,
         "state":"VIC",
         "vicSuburb":"QUANDONG"
      },
      {
         "postcode":3099,
         "state":"VIC",
         "vicSuburb":"HURSTBRIDGE"
      },
      {
         "postcode":3139,
         "state":"VIC",
         "vicSuburb":"YELLINGBO"
      },
      {
         "postcode":3019,
         "state":"VIC",
         "vicSuburb":"BRAYBROOK NORTH"
      },
      {
         "postcode":3207,
         "state":"VIC",
         "vicSuburb":"PORT MELBOURNE"
      },
      {
         "postcode":3001,
         "state":"VIC",
         "vicSuburb":"MELBOURNE"
      },
      {
         "postcode":3254,
         "state":"VIC",
         "vicSuburb":"COROROOKE"
      },
      {
         "postcode":3222,
         "state":"VIC",
         "vicSuburb":"MANNERIM"
      },
      {
         "postcode":3152,
         "state":"VIC",
         "vicSuburb":"WANTIRNA"
      },
      {
         "postcode":3139,
         "state":"VIC",
         "vicSuburb":"WANDIN NORTH"
      },
      {
         "postcode":3148,
         "state":"VIC",
         "vicSuburb":"CHADSTONE CENTRE"
      },
      {
         "postcode":3235,
         "state":"VIC",
         "vicSuburb":"PENNYROYAL"
      },
      {
         "postcode":3265,
         "state":"VIC",
         "vicSuburb":"BOORCAN"
      },
      {
         "postcode":3064,
         "state":"VIC",
         "vicSuburb":"ROXBURGH PARK"
      },
      {
         "postcode":3249,
         "state":"VIC",
         "vicSuburb":"WARRION"
      },
      {
         "postcode":3212,
         "state":"VIC",
         "vicSuburb":"POINT WILSON"
      },
      {
         "postcode":3185,
         "state":"VIC",
         "vicSuburb":"RIPPONLEA"
      },
      {
         "postcode":3188,
         "state":"VIC",
         "vicSuburb":"HAMPTON NORTH"
      },
      {
         "postcode":3125,
         "state":"VIC",
         "vicSuburb":"BENNETTSWOOD"
      },
      {
         "postcode":3156,
         "state":"VIC",
         "vicSuburb":"MOUNTAIN GATE"
      },
      {
         "postcode":3018,
         "state":"VIC",
         "vicSuburb":"SEAHOLME"
      },
      {
         "postcode":3216,
         "state":"VIC",
         "vicSuburb":"WAURN PONDS"
      },
      {
         "postcode":3151,
         "state":"VIC",
         "vicSuburb":"BURWOOD HEIGHTS"
      },
      {
         "postcode":3174,
         "state":"VIC",
         "vicSuburb":"NOBLE PARK EAST"
      },
      {
         "postcode":3265,
         "state":"VIC",
         "vicSuburb":"THE SISTERS"
      },
      {
         "postcode":3034,
         "state":"VIC",
         "vicSuburb":"AVONDALE HEIGHTS"
      },
      {
         "postcode":3121,
         "state":"VIC",
         "vicSuburb":"BURNLEY"
      },
      {
         "postcode":3116,
         "state":"VIC",
         "vicSuburb":"CHIRNSIDE PARK"
      },
      {
         "postcode":3193,
         "state":"VIC",
         "vicSuburb":"CROMER"
      },
      {
         "postcode":3127,
         "state":"VIC",
         "vicSuburb":"SURREY HILLS"
      },
      {
         "postcode":3168,
         "state":"VIC",
         "vicSuburb":"CLAYTON"
      },
      {
         "postcode":3045,
         "state":"VIC",
         "vicSuburb":"MELBOURNE AIRPORT"
      },
      {
         "postcode":3136,
         "state":"VIC",
         "vicSuburb":"CROYDON HILLS"
      },
      {
         "postcode":3196,
         "state":"VIC",
         "vicSuburb":"CHELSEA HEIGHTS"
      },
      {
         "postcode":3239,
         "state":"VIC",
         "vicSuburb":"CARLISLE RIVER"
      },
      {
         "postcode":3260,
         "state":"VIC",
         "vicSuburb":"KOALLAH"
      },
      {
         "postcode":3135,
         "state":"VIC",
         "vicSuburb":"HEATHMONT"
      },
      {
         "postcode":3215,
         "state":"VIC",
         "vicSuburb":"BELL PARK"
      },
      {
         "postcode":3060,
         "state":"VIC",
         "vicSuburb":"FAWKNER EAST"
      },
      {
         "postcode":3134,
         "state":"VIC",
         "vicSuburb":"WARRANWOOD"
      },
      {
         "postcode":3175,
         "state":"VIC",
         "vicSuburb":"DANDENONG NORTH"
      },
      {
         "postcode":3260,
         "state":"VIC",
         "vicSuburb":"POMBORNEIT"
      },
      {
         "postcode":3072,
         "state":"VIC",
         "vicSuburb":"NORTHLAND CENTRE"
      },
      {
         "postcode":3122,
         "state":"VIC",
         "vicSuburb":"HAWTHORN NORTH"
      },
      {
         "postcode":3241,
         "state":"VIC",
         "vicSuburb":"WINCHELSEA"
      },
      {
         "postcode":3207,
         "state":"VIC",
         "vicSuburb":"GARDEN CITY"
      },
      {
         "postcode":3094,
         "state":"VIC",
         "vicSuburb":"MONTMORENCY"
      },
      {
         "postcode":3075,
         "state":"VIC",
         "vicSuburb":"LALOR PLAZA"
      },
      {
         "postcode":3251,
         "state":"VIC",
         "vicSuburb":"CUNDARE NORTH"
      },
      {
         "postcode":3022,
         "state":"VIC",
         "vicSuburb":"DEER PARK EAST"
      },
      {
         "postcode":3233,
         "state":"VIC",
         "vicSuburb":"CAPE OTWAY"
      },
      {
         "postcode":3090,
         "state":"VIC",
         "vicSuburb":"PLENTY"
      },
      {
         "postcode":3168,
         "state":"VIC",
         "vicSuburb":"NOTTING HILL"
      },
      {
         "postcode":3042,
         "state":"VIC",
         "vicSuburb":"NIDDRIE"
      },
      {
         "postcode":3221,
         "state":"VIC",
         "vicSuburb":"WALLINGTON"
      },
      {
         "postcode":3249,
         "state":"VIC",
         "vicSuburb":"BARONGAROOK WEST"
      },
      {
         "postcode":3249,
         "state":"VIC",
         "vicSuburb":"IRREWARRA"
      },
      {
         "postcode":3132,
         "state":"VIC",
         "vicSuburb":"MITCHAM"
      },
      {
         "postcode":3221,
         "state":"VIC",
         "vicSuburb":"MOORABOOL"
      },
      {
         "postcode":3170,
         "state":"VIC",
         "vicSuburb":"WAVERLEY GARDENS"
      },
      {
         "postcode":3277,
         "state":"VIC",
         "vicSuburb":"NARINGAL EAST"
      },
      {
         "postcode":3289,
         "state":"VIC",
         "vicSuburb":"GAZETTE"
      },
      {
         "postcode":3171,
         "state":"VIC",
         "vicSuburb":"SANDOWN VILLAGE"
      },
      {
         "postcode":3085,
         "state":"VIC",
         "vicSuburb":"YALLAMBIE"
      },
      {
         "postcode":3138,
         "state":"VIC",
         "vicSuburb":"MOOROOLBARK"
      },
      {
         "postcode":3031,
         "state":"VIC",
         "vicSuburb":"KENSINGTON"
      },
      {
         "postcode":3124,
         "state":"VIC",
         "vicSuburb":"MIDDLE CAMBERWELL"
      },
      {
         "postcode":3198,
         "state":"VIC",
         "vicSuburb":"BELVEDERE PARK"
      },
      {
         "postcode":3260,
         "state":"VIC",
         "vicSuburb":"KARIAH"
      },
      {
         "postcode":3021,
         "state":"VIC",
         "vicSuburb":"KINGS PARK"
      },
      {
         "postcode":3023,
         "state":"VIC",
         "vicSuburb":"DEER PARK"
      },
      {
         "postcode":3152,
         "state":"VIC",
         "vicSuburb":"KNOX CITY CENTRE"
      },
      {
         "postcode":3029,
         "state":"VIC",
         "vicSuburb":"TARNEIT"
      },
      {
         "postcode":3154,
         "state":"VIC",
         "vicSuburb":"THE BASIN"
      },
      {
         "postcode":3048,
         "state":"VIC",
         "vicSuburb":"COOLAROO"
      },
      {
         "postcode":3268,
         "state":"VIC",
         "vicSuburb":"CURDIEVALE"
      },
      {
         "postcode":3012,
         "state":"VIC",
         "vicSuburb":"BROOKLYN"
      },
      {
         "postcode":3130,
         "state":"VIC",
         "vicSuburb":"BLACKBURN SOUTH"
      },
      {
         "postcode":3104,
         "state":"VIC",
         "vicSuburb":"GREYTHORN"
      },
      {
         "postcode":3228,
         "state":"VIC",
         "vicSuburb":"TORQUAY"
      },
      {
         "postcode":3270,
         "state":"VIC",
         "vicSuburb":"PETERBOROUGH"
      },
      {
         "postcode":3059,
         "state":"VIC",
         "vicSuburb":"GREENVALE"
      },
      {
         "postcode":3221,
         "state":"VIC",
         "vicSuburb":"SUGARLOAF"
      },
      {
         "postcode":3038,
         "state":"VIC",
         "vicSuburb":"WATERGARDENS"
      },
      {
         "postcode":3046,
         "state":"VIC",
         "vicSuburb":"GLENROY"
      },
      {
         "postcode":3239,
         "state":"VIC",
         "vicSuburb":"CHAPPLE VALE"
      },
      {
         "postcode":3237,
         "state":"VIC",
         "vicSuburb":"GELLIBRAND LOWER"
      },
      {
         "postcode":3011,
         "state":"VIC",
         "vicSuburb":"FOOTSCRAY"
      },
      {
         "postcode":3265,
         "state":"VIC",
         "vicSuburb":"FRAMLINGHAM EAST"
      },
      {
         "postcode":3097,
         "state":"VIC",
         "vicSuburb":"KANGAROO GROUND"
      },
      {
         "postcode":3249,
         "state":"VIC",
         "vicSuburb":"ONDIT"
      },
      {
         "postcode":3129,
         "state":"VIC",
         "vicSuburb":"MONT ALBERT NORTH"
      },
      {
         "postcode":3238,
         "state":"VIC",
         "vicSuburb":"HORDERN VALE"
      },
      {
         "postcode":3162,
         "state":"VIC",
         "vicSuburb":"CAULFIELD"
      },
      {
         "postcode":3223,
         "state":"VIC",
         "vicSuburb":"ST LEONARDS"
      },
      {
         "postcode":3231,
         "state":"VIC",
         "vicSuburb":"BIG HILL"
      },
      {
         "postcode":3093,
         "state":"VIC",
         "vicSuburb":"LOWER PLENTY"
      },
      {
         "postcode":3019,
         "state":"VIC",
         "vicSuburb":"BRAYBROOK"
      },
      {
         "postcode":3016,
         "state":"VIC",
         "vicSuburb":"WILLIAMSTOWN"
      },
      {
         "postcode":3066,
         "state":"VIC",
         "vicSuburb":"COLLINGWOOD NORTH"
      },
      {
         "postcode":3145,
         "state":"VIC",
         "vicSuburb":"CAULFIELD EAST"
      },
      {
         "postcode":3260,
         "state":"VIC",
         "vicSuburb":"CHOCOLYN"
      },
      {
         "postcode":3063,
         "state":"VIC",
         "vicSuburb":"OAKLANDS JUNCTION"
      },
      {
         "postcode":3099,
         "state":"VIC",
         "vicSuburb":"NUTFIELD"
      },
      {
         "postcode":3085,
         "state":"VIC",
         "vicSuburb":"MACLEOD"
      },
      {
         "postcode":3105,
         "state":"VIC",
         "vicSuburb":"BULLEEN"
      },
      {
         "postcode":3249,
         "state":"VIC",
         "vicSuburb":"TANYBRYN"
      },
      {
         "postcode":3243,
         "state":"VIC",
         "vicSuburb":"MURROON"
      },
      {
         "postcode":3032,
         "state":"VIC",
         "vicSuburb":"TRAVANCORE"
      },
      {
         "postcode":3084,
         "state":"VIC",
         "vicSuburb":"HEIDELBERG"
      },
      {
         "postcode":3126,
         "state":"VIC",
         "vicSuburb":"CAMBERWELL EAST"
      },
      {
         "postcode":3189,
         "state":"VIC",
         "vicSuburb":"WISHART"
      },
      {
         "postcode":3066,
         "state":"VIC",
         "vicSuburb":"COLLINGWOOD"
      },
      {
         "postcode":3228,
         "state":"VIC",
         "vicSuburb":"BELLBRAE"
      },
      {
         "postcode":3109,
         "state":"VIC",
         "vicSuburb":"THE PINES"
      },
      {
         "postcode":3268,
         "state":"VIC",
         "vicSuburb":"NEWFIELD"
      },
      {
         "postcode":3032,
         "state":"VIC",
         "vicSuburb":"ASCOT VALE"
      },
      {
         "postcode":3128,
         "state":"VIC",
         "vicSuburb":"BOX HILL"
      },
      {
         "postcode":3219,
         "state":"VIC",
         "vicSuburb":"WHITTINGTON"
      },
      {
         "postcode":3193,
         "state":"VIC",
         "vicSuburb":"BLACK ROCK NORTH"
      },
      {
         "postcode":3088,
         "state":"VIC",
         "vicSuburb":"SAINT HELENA"
      },
      {
         "postcode":3058,
         "state":"VIC",
         "vicSuburb":"MERLYNSTON"
      },
      {
         "postcode":3187,
         "state":"VIC",
         "vicSuburb":"NORTH ROAD"
      },
      {
         "postcode":3023,
         "state":"VIC",
         "vicSuburb":"BURNSIDE HEIGHTS"
      },
      {
         "postcode":3192,
         "state":"VIC",
         "vicSuburb":"CHELTENHAM EAST"
      },
      {
         "postcode":3214,
         "state":"VIC",
         "vicSuburb":"CORIO"
      },
      {
         "postcode":3274,
         "state":"VIC",
         "vicSuburb":"CARAMUT"
      },
      {
         "postcode":3055,
         "state":"VIC",
         "vicSuburb":"BRUNSWICK WEST"
      },
      {
         "postcode":3060,
         "state":"VIC",
         "vicSuburb":"FAWKNER NORTH"
      },
      {
         "postcode":3081,
         "state":"VIC",
         "vicSuburb":"BELLFIELD"
      },
      {
         "postcode":3160,
         "state":"VIC",
         "vicSuburb":"BELGRAVE HEIGHTS"
      },
      {
         "postcode":3183,
         "state":"VIC",
         "vicSuburb":"ST KILDA EAST"
      },
      {
         "postcode":3029,
         "state":"VIC",
         "vicSuburb":"HOPPERS CROSSING"
      },
      {
         "postcode":3250,
         "state":"VIC",
         "vicSuburb":"ELLIMINYT"
      },
      {
         "postcode":3012,
         "state":"VIC",
         "vicSuburb":"KINGSVILLE"
      },
      {
         "postcode":3139,
         "state":"VIC",
         "vicSuburb":"HODDLES CREEK"
      },
      {
         "postcode":3193,
         "state":"VIC",
         "vicSuburb":"BEAUMARIS"
      },
      {
         "postcode":3214,
         "state":"VIC",
         "vicSuburb":"NORTH SHORE"
      },
      {
         "postcode":3240,
         "state":"VIC",
         "vicSuburb":"MORIAC"
      },
      {
         "postcode":3038,
         "state":"VIC",
         "vicSuburb":"KEILOR LODGE"
      },
      {
         "postcode":3145,
         "state":"VIC",
         "vicSuburb":"CENTRAL PARK"
      },
      {
         "postcode":3005,
         "state":"VIC",
         "vicSuburb":"WORLD TRADE CENTRE"
      },
      {
         "postcode":3243,
         "state":"VIC",
         "vicSuburb":"GERANGAMETE"
      },
      {
         "postcode":3227,
         "state":"VIC",
         "vicSuburb":"BREAMLEA"
      },
      {
         "postcode":3121,
         "state":"VIC",
         "vicSuburb":"RICHMOND NORTH"
      },
      {
         "postcode":3121,
         "state":"VIC",
         "vicSuburb":"RICHMOND SOUTH"
      },
      {
         "postcode":3283,
         "state":"VIC",
         "vicSuburb":"KILLARNEY"
      },
      {
         "postcode":3144,
         "state":"VIC",
         "vicSuburb":"MALVERN NORTH"
      },
      {
         "postcode":3206,
         "state":"VIC",
         "vicSuburb":"MIDDLE PARK"
      },
      {
         "postcode":3095,
         "state":"VIC",
         "vicSuburb":"ELTHAM NORTH"
      },
      {
         "postcode":3026,
         "state":"VIC",
         "vicSuburb":"LAVERTON NORTH"
      },
      {
         "postcode":3020,
         "state":"VIC",
         "vicSuburb":"SUNSHINE WEST"
      },
      {
         "postcode":3249,
         "state":"VIC",
         "vicSuburb":"DREEITE"
      },
      {
         "postcode":3249,
         "state":"VIC",
         "vicSuburb":"SWAN MARSH"
      },
      {
         "postcode":3149,
         "state":"VIC",
         "vicSuburb":"PINEWOOD"
      },
      {
         "postcode":3283,
         "state":"VIC",
         "vicSuburb":"CROSSLEY"
      },
      {
         "postcode":3240,
         "state":"VIC",
         "vicSuburb":"GHERANG"
      },
      {
         "postcode":3283,
         "state":"VIC",
         "vicSuburb":"YARPTURK"
      },
      {
         "postcode":3079,
         "state":"VIC",
         "vicSuburb":"IVANHOE EAST"
      },
      {
         "postcode":3220,
         "state":"VIC",
         "vicSuburb":"GEELONG"
      },
      {
         "postcode":3002,
         "state":"VIC",
         "vicSuburb":"EAST MELBOURNE"
      },
      {
         "postcode":3227,
         "state":"VIC",
         "vicSuburb":"CONNEWARRE"
      },
      {
         "postcode":3266,
         "state":"VIC",
         "vicSuburb":"ELINGAMITE NORTH"
      },
      {
         "postcode":3249,
         "state":"VIC",
         "vicSuburb":"DREEITE SOUTH"
      },
      {
         "postcode":3265,
         "state":"VIC",
         "vicSuburb":"TAROON"
      },
      {
         "postcode":3283,
         "state":"VIC",
         "vicSuburb":"YANGERY"
      },
      {
         "postcode":3195,
         "state":"VIC",
         "vicSuburb":"WATERWAYS"
      },
      {
         "postcode":3088,
         "state":"VIC",
         "vicSuburb":"BRIAR HILL"
      },
      {
         "postcode":3139,
         "state":"VIC",
         "vicSuburb":"BEENAK"
      },
      {
         "postcode":3133,
         "state":"VIC",
         "vicSuburb":"VERMONT SOUTH"
      },
      {
         "postcode":3049,
         "state":"VIC",
         "vicSuburb":"CALDER PARK"
      },
      {
         "postcode":3225,
         "state":"VIC",
         "vicSuburb":"SWAN BAY"
      },
      {
         "postcode":3143,
         "state":"VIC",
         "vicSuburb":"ARMADALE"
      },
      {
         "postcode":3144,
         "state":"VIC",
         "vicSuburb":"MALVERN"
      },
      {
         "postcode":3042,
         "state":"VIC",
         "vicSuburb":"AIRPORT WEST"
      },
      {
         "postcode":3037,
         "state":"VIC",
         "vicSuburb":"HILLSIDE"
      },
      {
         "postcode":3233,
         "state":"VIC",
         "vicSuburb":"MARENGO"
      },
      {
         "postcode":3063,
         "state":"VIC",
         "vicSuburb":"YUROKE"
      },
      {
         "postcode":3193,
         "state":"VIC",
         "vicSuburb":"BLACK ROCK"
      },
      {
         "postcode":3024,
         "state":"VIC",
         "vicSuburb":"WYNDHAM VALE"
      },
      {
         "postcode":3269,
         "state":"VIC",
         "vicSuburb":"PRINCETOWN"
      },
      {
         "postcode":3010,
         "state":"VIC",
         "vicSuburb":"UNIVERSITY OF MELBOURNE"
      },
      {
         "postcode":3023,
         "state":"VIC",
         "vicSuburb":"BURNSIDE"
      },
      {
         "postcode":3268,
         "state":"VIC",
         "vicSuburb":"AYRFORD"
      },
      {
         "postcode":3289,
         "state":"VIC",
         "vicSuburb":"PURDEET"
      },
      {
         "postcode":3136,
         "state":"VIC",
         "vicSuburb":"CROYDON"
      },
      {
         "postcode":3103,
         "state":"VIC",
         "vicSuburb":"BALWYN EAST"
      },
      {
         "postcode":3024,
         "state":"VIC",
         "vicSuburb":"MAMBOURIN"
      },
      {
         "postcode":3242,
         "state":"VIC",
         "vicSuburb":"BIRREGURRA"
      },
      {
         "postcode":3285,
         "state":"VIC",
         "vicSuburb":"ROSEBROOK"
      },
      {
         "postcode":3266,
         "state":"VIC",
         "vicSuburb":"SIMPSON"
      },
      {
         "postcode":3156,
         "state":"VIC",
         "vicSuburb":"FERNTREE GULLY"
      },
      {
         "postcode":3221,
         "state":"VIC",
         "vicSuburb":"CERES"
      },
      {
         "postcode":3136,
         "state":"VIC",
         "vicSuburb":"CROYDON NORTH"
      },
      {
         "postcode":3266,
         "state":"VIC",
         "vicSuburb":"JANCOURT"
      },
      {
         "postcode":3133,
         "state":"VIC",
         "vicSuburb":"VERMONT"
      },
      {
         "postcode":3177,
         "state":"VIC",
         "vicSuburb":"EUMEMMERRING"
      },
      {
         "postcode":3051,
         "state":"VIC",
         "vicSuburb":"NORTH MELBOURNE"
      },
      {
         "postcode":3217,
         "state":"VIC",
         "vicSuburb":"DEAKIN UNIVERSITY"
      },
      {
         "postcode":3071,
         "state":"VIC",
         "vicSuburb":"THORNBURY"
      },
      {
         "postcode":3025,
         "state":"VIC",
         "vicSuburb":"ALTONA GATE"
      },
      {
         "postcode":3028,
         "state":"VIC",
         "vicSuburb":"SEABROOK"
      },
      {
         "postcode":3260,
         "state":"VIC",
         "vicSuburb":"BUNGADOR"
      },
      {
         "postcode":3169,
         "state":"VIC",
         "vicSuburb":"CLAYTON SOUTH"
      },
      {
         "postcode":3216,
         "state":"VIC",
         "vicSuburb":"GROVEDALE EAST"
      },
      {
         "postcode":3068,
         "state":"VIC",
         "vicSuburb":"FITZROY NORTH"
      },
      {
         "postcode":3156,
         "state":"VIC",
         "vicSuburb":"LYSTERFIELD"
      },
      {
         "postcode":3251,
         "state":"VIC",
         "vicSuburb":"BEEAC"
      },
      {
         "postcode":3121,
         "state":"VIC",
         "vicSuburb":"BURNLEY NORTH"
      },
      {
         "postcode":3054,
         "state":"VIC",
         "vicSuburb":"PRINCES HILL"
      },
      {
         "postcode":3239,
         "state":"VIC",
         "vicSuburb":"GELLIBRAND"
      },
      {
         "postcode":3199,
         "state":"VIC",
         "vicSuburb":"FRANKSTON EAST"
      },
      {
         "postcode":3144,
         "state":"VIC",
         "vicSuburb":"KOOYONG"
      },
      {
         "postcode":3147,
         "state":"VIC",
         "vicSuburb":"ASHBURTON"
      },
      {
         "postcode":3185,
         "state":"VIC",
         "vicSuburb":"ELSTERNWICK"
      },
      {
         "postcode":3221,
         "state":"VIC",
         "vicSuburb":"STAUGHTON VALE"
      },
      {
         "postcode":3236,
         "state":"VIC",
         "vicSuburb":"MOUNT SABINE"
      },
      {
         "postcode":3056,
         "state":"VIC",
         "vicSuburb":"BRUNSWICK LOWER"
      },
      {
         "postcode":3264,
         "state":"VIC",
         "vicSuburb":"TERANG"
      },
      {
         "postcode":3043,
         "state":"VIC",
         "vicSuburb":"GOWANBRAE"
      },
      {
         "postcode":3156,
         "state":"VIC",
         "vicSuburb":"LYSTERFIELD SOUTH"
      },
      {
         "postcode":3194,
         "state":"VIC",
         "vicSuburb":"MOORABBIN AIRPORT"
      },
      {
         "postcode":3231,
         "state":"VIC",
         "vicSuburb":"AIREYS INLET"
      },
      {
         "postcode":3033,
         "state":"VIC",
         "vicSuburb":"KEILOR EAST"
      },
      {
         "postcode":3216,
         "state":"VIC",
         "vicSuburb":"FRESHWATER CREEK"
      },
      {
         "postcode":3183,
         "state":"VIC",
         "vicSuburb":"BALACLAVA"
      },
      {
         "postcode":3278,
         "state":"VIC",
         "vicSuburb":"PURNIM"
      },
      {
         "postcode":3072,
         "state":"VIC",
         "vicSuburb":"PRESTON WEST"
      },
      {
         "postcode":3283,
         "state":"VIC",
         "vicSuburb":"WARRONG"
      },
      {
         "postcode":3108,
         "state":"VIC",
         "vicSuburb":"DONCASTER"
      },
      {
         "postcode":3260,
         "state":"VIC",
         "vicSuburb":"CARPENDEIT"
      },
      {
         "postcode":3260,
         "state":"VIC",
         "vicSuburb":"WEERITE"
      },
      {
         "postcode":3052,
         "state":"VIC",
         "vicSuburb":"PARKVILLE"
      },
      {
         "postcode":3188,
         "state":"VIC",
         "vicSuburb":"HAMPTON EAST"
      },
      {
         "postcode":3233,
         "state":"VIC",
         "vicSuburb":"APOLLO BAY"
      },
      {
         "postcode":3249,
         "state":"VIC",
         "vicSuburb":"KAWARREN"
      },
      {
         "postcode":3285,
         "state":"VIC",
         "vicSuburb":"YAMBUK"
      },
      {
         "postcode":3150,
         "state":"VIC",
         "vicSuburb":"WHEELERS HILL"
      },
      {
         "postcode":3281,
         "state":"VIC",
         "vicSuburb":"WINSLOW"
      },
      {
         "postcode":3079,
         "state":"VIC",
         "vicSuburb":"IVANHOE NORTH"
      },
      {
         "postcode":3265,
         "state":"VIC",
         "vicSuburb":"FRAMLINGHAM"
      },
      {
         "postcode":3084,
         "state":"VIC",
         "vicSuburb":"VIEWBANK"
      },
      {
         "postcode":3260,
         "state":"VIC",
         "vicSuburb":"TANDAROOK"
      },
      {
         "postcode":3267,
         "state":"VIC",
         "vicSuburb":"SCOTTS CREEK"
      },
      {
         "postcode":3221,
         "state":"VIC",
         "vicSuburb":"LOVELY BANKS"
      },
      {
         "postcode":3268,
         "state":"VIC",
         "vicSuburb":"NIRRANDA"
      },
      {
         "postcode":3171,
         "state":"VIC",
         "vicSuburb":"SPRINGVALE"
      },
      {
         "postcode":3004,
         "state":"VIC",
         "vicSuburb":"MELBOURNE"
      },
      {
         "postcode":3236,
         "state":"VIC",
         "vicSuburb":"FORREST"
      },
      {
         "postcode":3049,
         "state":"VIC",
         "vicSuburb":"WESTMEADOWS"
      },
      {
         "postcode":3142,
         "state":"VIC",
         "vicSuburb":"TOORAK"
      },
      {
         "postcode":3151,
         "state":"VIC",
         "vicSuburb":"BURWOOD EAST"
      },
      {
         "postcode":3221,
         "state":"VIC",
         "vicSuburb":"MURGHEBOLUC"
      },
      {
         "postcode":3131,
         "state":"VIC",
         "vicSuburb":"NUNAWADING"
      },
      {
         "postcode":3160,
         "state":"VIC",
         "vicSuburb":"BELGRAVE"
      },
      {
         "postcode":3115,
         "state":"VIC",
         "vicSuburb":"WONGA PARK"
      },
      {
         "postcode":3221,
         "state":"VIC",
         "vicSuburb":"KENNETT RIVER"
      }
   ];

   return suburbs
  }

}
